[workspace]
members = ["db_manager","interface_types", "server_main","user_auth"]
exclude = ["db_manager/migration"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["April <zhao@zhaocloud.work>"]
description = "A Rust backend for the ShangDi server project"
