[package]
name = "interface_types"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
prost = "0.14.1"
prost-types = "0.14.1"

[build-dependencies]
prost-build = "0.14.1"
